from .cep_service import fetch_address_by_cep
from .email_service import send_email, send_reset_password_email, send_verification_email
from .circuit_breaker_service import get_circuit_breaker
from .http_client_manager import HTTPClientManager, get_http_client_manager
from .external_api_service import ExternalAPIService
