from typing import Optional
from pydantic import EmailStr

from app.core.schemas import BaseSchema

class GoogleCallbackRequest(BaseSchema):
    """Request payload from Angular after Google OAuth redirect"""
    code: str  # Authorization code from Google
    code_verifier: str  # PKCE code_verifier generated by Angular

# Google OAuth Response
class GoogleTokenResponse(BaseSchema):
    access_token: str
    expires_in: int
    scope: str
    token_type: str
    id_token: str
    refresh_token: Optional[str] = None


class GoogleUserInfo(BaseSchema):
    sub: str  # Google user ID
    email: EmailStr
    email_verified: bool
    name: Optional[str]
    picture: Optional[str]
    given_name: Optional[str]
    family_name: Optional[str]
    locale: Optional[str]